CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    textual_content VARCHAR(1000) NOT NULL,
    author_id       BIGINT        NOT NULL,
    event_id        BIGINT        NOT NULL,
    create_time     TIMESTAMP     NOT NULL,
    patch_time      TIMESTAMP,
    approved        BOOLEAN DEFAULT TRUE NOT NULL,

    CONSTRAINT pk_comment PRIMARY KEY (id)
);