DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id    BIGINT NOT NULL,
    event_id        BIGINT NOT NULL,
    status          VARCHAR(15) NOT NULL,
    created_at      TIMESTAMP NOT NULL
);