DROP TABLE IF EXISTS views CASCADE;
DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE IF NOT EXISTS categories(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000),
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    confirmed_requests int DEFAULT 0,
    created_on timestamp NOT NULL,
    published_on timestamp,
    description varchar(7000),
    event_date timestamp NOT NULL,
    initiator_id BIGINT NOT NULL,
    paid BOOLEAN,
    participant_limit int,
    state varchar(50) NOT NULL,
    request_moderation BOOLEAN,
    title varchar(120),
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    commenting BOOLEAN
);

CREATE TABLE IF NOT EXISTS compilations(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events(
    compilation_id BIGINT REFERENCES compilations(compilation_id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(event_id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL
);